---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-infra-secrets
  labels:
    app: {{ .Release.Name }}-AllApps
    app.business.client: {{ .Values.ClientName }}
    environment: {{ .Values.environment }}
type: Opaque    
data:
  mariadb_password: {{ randAlphaNum 32 | b64enc | quote }}
  mariadb_root_password: {{ randAlphaNum 32 | b64enc | quote }}
  slack_webhook: {{ randAlphaNum 32 | b64enc | quote }} 