---
apiVersion: v1
kind: Service
metadata:
  name: producer
  labels:
    app: {{ .Release.Name }}-producer
    environment: {{ .Values.environment }}
    app.business.client: {{ .Values.ClientName }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9090"
    filter.by.port.name: "true"
spec:
  selector:
    app: {{ .Release.Name }}-producer
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: monitoring
      protocol: TCP
      port: 9090
      targetPort: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: {{ .Release.Name }}-producer
    app.depends: {{ .Release.Name }}-rabbitmq
    app.business.client: {{ .Values.ClientName }}
    environment: {{ .Values.environment }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-producer    
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-producer
        environment: {{ .Values.environment }}
        app.business.client: {{ .Values.ClientName }}
    spec:
      containers:
        - name: {{ .Release.Name }}-producer
          image: {{ .Values.producer.image }}:{{ .Values.producer.tag }}
          imagePullPolicy: {{ .Values.producer.imagePullPolicy }}
          env:
          - name: mqtthost
            value: {{ .Release.Name }}-rabbitmq
          - name: mqttvhost
            value: {{ .Values.global.configs.mqttvhost }}
          - name: queue
            value: {{ .Values.global.configs.queue }}
          - name: destination_queue
            value: {{ .Values.global.configs.destination_queue }}
          - name: destination_RK
            value: {{ .Values.global.configs.destination_rk }}
          - name: mqttuser
            value: {{ .Values.rabbitmq.auth.username }}
          - name: mqttpass
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-rabbitmq
                key: rabbitmq-password
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 5




