apiVersion: v1
kind: Service
metadata:
  name: consumer
  labels:
    app: {{ .Release.Name }}-consumer
    app.business.client: {{ .Values.ClientName }}
    environment: {{ .Values.environment }}
  annotations:
    prometheus.io/scrape: 'true'
    filter.by.port.name: 'true'
spec:
  selector:
    app: {{ .Release.Name }}-consumer
  ports:
    - name: metrics
      protocol: TCP
      port: 9090

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-consumer-sa

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-consumer-cr
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-consumer-cr-binding
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-consumer-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-consumer-cr
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: {{ .Release.Name }}-consumer
    app.depends: {{ .Release.Name }}-rabbitmq
    app.business.client: {{ .Values.ClientName }}
    environment: {{ .Values.environment }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-consumer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-consumer
        app.depends: {{ .Release.Name }}-rabbitmq
        environment: {{ .Values.environment }}    
    spec:
      serviceAccountName: {{ .Release.Name }}-consumer-sa
      containers:
        - name: consumer
          image: {{ .Values.consumer.image }}:{{ .Values.consumer.tag }}
          imagePullPolicy: {{ .Values.consumer.imagePullPolicy }}
          env:
          - name: mqtthost
            value: {{ .Release.Name }}-rabbitmq
          - name: mqttvhost
            value: {{ .Values.global.configs.mqttvhost }}
          - name: queue
            value: {{ .Values.global.configs.queue }}
          - name: destination_queue
            value: {{ .Values.global.configs.destination_queue }}
          - name: destination_RK
            value: {{ .Values.global.configs.destination_rk }}
          - name: mqttuser
            value: {{ .Values.rabbitmq.auth.username }}
          - name: mqttpass
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-rabbitmq
                key: rabbitmq-password
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 5
