---
apiVersion: v1
kind: Service
metadata:
  name: dbwriter
  namespace: default
  labels:
    app: {{ .Release.Name }}-dbwriter
    app.business.client: {{ .Values.ClientName }}
    environment: {{ .Values.environment }}
  annotations:
    prometheus.io/scrape: 'true'
    filter.by.port.name: 'true'
spec:
  selector:
    app: dbwriter
  ports:
    - name: metrics
      protocol: TCP     
      port: 9090 
      

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbwriter
  namespace: default
  labels:
    app: {{ .Release.Name }}-dbwriter
    app.depends: {{ .Release.Name }}-rabbitmq
    app.business.client: {{ .Values.ClientName }}
    environment: {{ .Values.environment }}  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-dbwriter
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-dbwriter
    spec:
      containers:
        - name: dbwriter
          image: {{ .Values.dbwriter.image }}:{{ .Values.dbwriter.tag }}
          imagePullPolicy: Always   
          env:
          - name: MARIADB_HOST
            value: "mariadb"
          - name: MARIADB_DATABASE
            value: {{ .Values.mariadb.config.database_name }}
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-infra-secrets
                key: mariadb_root_password
          - name: MARIADB_USER
            value: root
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-infra-secrets
                key: mariadb_root_password
          - name: mqttport
            value: "5672"
          - name: mqtthost
            value: {{ .Release.Name }}-rabbitmq
          - name: mqttvhost
            value: {{ .Values.global.configs.mqttvhost }}
          - name: queue
            value: {{ .Values.global.configs.queue_client_status }}
          - name: destination_queue
            value: {{ .Values.global.configs.destination_queue }}
          - name: destination_RK
            value: {{ .Values.global.configs.destination_rk }}
          - name: mqttuser
            value: {{ .Values.rabbitmq.auth.username }}
          - name: mqttpass
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-rabbitmq
                key: rabbitmq-password
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 5